/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author Rodo
 */
public class viewProveedoresEditar extends javax.swing.JPanel {

    /**
     * Creates new form viewProveedoresEditar
     */
    public viewProveedoresEditar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jl_nombre = new javax.swing.JLabel();
        jl_RFC = new javax.swing.JLabel();
        jl_calle = new javax.swing.JLabel();
        jl_numero = new javax.swing.JLabel();
        jl_colonia = new javax.swing.JLabel();
        jl_ciudad = new javax.swing.JLabel();
        jl_estado = new javax.swing.JLabel();
        jl_contacto = new javax.swing.JLabel();
        jl_telefono = new javax.swing.JLabel();
        jl_eMail = new javax.swing.JLabel();
        jtf_name = new javax.swing.JTextField();
        JTF_calle = new javax.swing.JTextField();
        jtf_rfc = new javax.swing.JTextField();
        jtf_estado = new javax.swing.JTextField();
        jtf_city = new javax.swing.JTextField();
        jtf_num = new javax.swing.JTextField();
        jtf_colonia = new javax.swing.JTextField();
        jtf_nameContact = new javax.swing.JTextField();
        jtf_phone = new javax.swing.JTextField();
        jtf_mail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jl_id = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(244, 116, 56));

        jPanel2.setBackground(new java.awt.Color(246, 57, 11));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel1.setText("Editar datos del proveedor");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jl_nombre.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jl_nombre.setText("Nombre");

        jl_RFC.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jl_RFC.setText("RFC");

        jl_calle.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jl_calle.setText("Calle");

        jl_numero.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jl_numero.setText("No.");

        jl_colonia.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jl_colonia.setText("Colonia");

        jl_ciudad.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jl_ciudad.setText("Ciudad");

        jl_estado.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jl_estado.setText("Estado");

        jl_contacto.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jl_contacto.setText("Nom. Contacto");

        jl_telefono.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jl_telefono.setText("Telefono");

        jl_eMail.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jl_eMail.setText("e-mail");

        jtf_name.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        JTF_calle.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        JTF_calle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF_calleActionPerformed(evt);
            }
        });

        jtf_rfc.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        jtf_estado.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jtf_estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_estadoActionPerformed(evt);
            }
        });

        jtf_city.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jtf_city.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_cityActionPerformed(evt);
            }
        });

        jtf_num.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        jtf_colonia.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        jtf_nameContact.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        jtf_phone.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        jtf_mail.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel2.setText("ID del proveedor:");

        jl_id.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jl_id.setText("oooooooooooo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jl_colonia)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtf_name, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                    .addComponent(jtf_rfc, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                    .addComponent(JTF_calle)
                    .addComponent(jtf_num, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_colonia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_eMail, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jl_contacto, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtf_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_mail, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jtf_nameContact, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jtf_city, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                        .addComponent(jtf_estado, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(32, 32, 32))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jl_id)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jl_nombre)
                        .addComponent(jl_RFC)
                        .addComponent(jl_calle)
                        .addComponent(jl_numero))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 248, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jl_estado, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jl_telefono, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jl_ciudad, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addGap(203, 203, 203)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jl_id))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_city, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtf_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_rfc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtf_nameContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jl_contacto))
                    .addComponent(JTF_calle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtf_num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_colonia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_mail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_colonia)
                    .addComponent(jl_eMail))
                .addGap(0, 33, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(90, 90, 90)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jl_ciudad)
                        .addComponent(jl_nombre))
                    .addGap(11, 11, 11)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jl_estado)
                        .addComponent(jl_RFC))
                    .addGap(11, 11, 11)
                    .addComponent(jl_calle)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jl_telefono)
                        .addComponent(jl_numero))
                    .addContainerGap(70, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_cityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_cityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_cityActionPerformed

    private void JTF_calleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF_calleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTF_calleActionPerformed

    private void jtf_estadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_estadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_estadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField JTF_calle;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JLabel jl_RFC;
    public javax.swing.JLabel jl_calle;
    public javax.swing.JLabel jl_ciudad;
    public javax.swing.JLabel jl_colonia;
    public javax.swing.JLabel jl_contacto;
    public javax.swing.JLabel jl_eMail;
    public javax.swing.JLabel jl_estado;
    public javax.swing.JLabel jl_id;
    public javax.swing.JLabel jl_nombre;
    public javax.swing.JLabel jl_numero;
    public javax.swing.JLabel jl_telefono;
    public javax.swing.JTextField jtf_city;
    public javax.swing.JTextField jtf_colonia;
    public javax.swing.JTextField jtf_estado;
    public javax.swing.JTextField jtf_mail;
    public javax.swing.JTextField jtf_name;
    public javax.swing.JTextField jtf_nameContact;
    public javax.swing.JTextField jtf_num;
    public javax.swing.JTextField jtf_phone;
    public javax.swing.JTextField jtf_rfc;
    // End of variables declaration//GEN-END:variables
}
